// FC26 Calculator — Squad saves. Re-import via the "Import Saves" button.
window.SQUAD_SAVES = {
  "folders": [
    {
      "id": "81jzisi",
      "name": "Attackers",
      "open": true,
      "players": [],
      "subfolders": [
        {
          "name": "Freight Trains (Strikers only)",
          "open": false,
          "players": [
            {
              "name": "Haaland TOTY",
              "roles": [
                "ST"
              ],
              "archetypePrimary": "Freight Train",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 90,
                "baseSprint": 96,
                "baseAgility": 87,
                "heightCm": 195,
                "weight": 94,
                "strength": 96,
                "balance": 87,
                "accelType": "lengthy",
                "buildType": "stocky",
                "activePS": [
                  "rapid_plus",
                  "enforcer_plus",
                  "low_driven_plus",
                  "finesse",
                  "chip_shot",
                  "first_time",
                  "power_shot",
                  "precision_header"
                ],
                "shortPass": 90,
                "longPass": 80,
                "vision": 88,
                "crossing": 70,
                "curve": 90,
                "fkAccuracy": 70,
                "standTackle": 56,
                "slideTackle": 35,
                "interceptions": 52,
                "headingAcc": 94,
                "defAwareness": 46,
                "aggression": 92,
                "jumping": 95,
                "finishing": 98,
                "shotPower": 98,
                "longShots": 91,
                "volleys": 96,
                "attPositioning": 99,
                "composure": 94,
                "reactions": 97,
                "ballControl": 90,
                "dribbling": 90,
                "stamina": 88
              },
              "effA": 76,
              "effS": 115,
              "effG": 84,
              "effT": 110,
              "effSlip": 72,
              "effPassShort": 100,
              "effPassLong": 90,
              "effPassThrough": 107,
              "effPassCross": 87,
              "effDefTackle": 63,
              "effDefPos": 48,
              "effDefInt": 60,
              "effDefAer": 121,
              "effDefBully": 96,
              "effDefSlide": 46,
              "effShootFin": 119,
              "effShootPwr": 124,
              "effShootFine": 120,
              "effShootVol": 117,
              "effShootLdr": 123,
              "effShootFk": 77,
              "colorTags": [
                {
                  "fill": "#0043ff",
                  "border": "#0000ff"
                }
              ]
            },
            {
              "name": "Lukaku",
              "roles": [
                "ST"
              ],
              "archetypePrimary": "Bulldozer",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "hunter",
                "baseAccel": 90,
                "baseSprint": 90,
                "baseAgility": 96,
                "heightCm": 191,
                "weight": 94,
                "strength": 95,
                "balance": 86,
                "accelType": "controlled",
                "buildType": "very_stocky",
                "activePS": [
                  "quickstep_plus",
                  "rapid",
                  "enforcer_plus",
                  "first_touch",
                  "technical",
                  "incisive",
                  "bruiser_plus",
                  "power_shot",
                  "low_driven"
                ],
                "shortPass": 83,
                "longPass": 73,
                "vision": 85,
                "crossing": 71,
                "curve": 77,
                "fkAccuracy": 62,
                "standTackle": 42,
                "slideTackle": 32,
                "interceptions": 38,
                "headingAcc": 86,
                "defAwareness": 37,
                "aggression": 92,
                "jumping": 93,
                "finishing": 91,
                "shotPower": 94,
                "longShots": 90,
                "volleys": 76,
                "attPositioning": 92,
                "composure": 93,
                "reactions": 86,
                "ballControl": 91,
                "dribbling": 89,
                "stamina": 76
              },
              "effA": 95,
              "effS": 99,
              "effG": 96,
              "effT": 117,
              "effSlip": 93,
              "effPassShort": 86,
              "effPassLong": 76,
              "effPassThrough": 97,
              "effPassCross": 74,
              "effDefTackle": 51,
              "effDefPos": 38,
              "effDefInt": 40,
              "effDefAer": 111,
              "effDefBully": 108,
              "effDefSlide": 43,
              "effShootFin": 106,
              "effShootPwr": 122,
              "effShootFine": 87,
              "effShootVol": 94,
              "effShootLdr": 117,
              "effShootFk": 65,
              "colorTags": [
                {
                  "fill": "#000000",
                  "border": "#ffe700"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "Haaland TOTS",
              "roles": [
                "ST"
              ],
              "archetypePrimary": "Freight Train",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 91,
                "baseSprint": 97,
                "baseAgility": 90,
                "heightCm": 195,
                "weight": 94,
                "strength": 96,
                "balance": 90,
                "accelType": "controlled",
                "buildType": "stocky",
                "activePS": [
                  "low_driven_plus",
                  "first_time",
                  "power_shot",
                  "enforcer",
                  "quickstep_plus",
                  "finesse_plus",
                  "precision_header",
                  "game_changer",
                  "chip_shot",
                  "tiki_taka"
                ],
                "shortPass": 91,
                "longPass": 83,
                "vision": 90,
                "crossing": 72,
                "curve": 93,
                "fkAccuracy": 75,
                "standTackle": 56,
                "slideTackle": 35,
                "interceptions": 52,
                "headingAcc": 94,
                "defAwareness": 46,
                "aggression": 92,
                "jumping": 95,
                "finishing": 99,
                "shotPower": 99,
                "longShots": 92,
                "volleys": 97,
                "attPositioning": 99,
                "composure": 95,
                "reactions": 98,
                "ballControl": 91,
                "dribbling": 91,
                "stamina": 88
              },
              "effA": 92,
              "effS": 102,
              "effG": 89,
              "effT": 106,
              "effSlip": 75,
              "effPassShort": 107,
              "effPassLong": 94,
              "effPassThrough": 111,
              "effPassCross": 90,
              "effDefTackle": 62,
              "effDefPos": 47,
              "effDefInt": 59,
              "effDefAer": 120,
              "effDefBully": 96,
              "effDefSlide": 45,
              "effShootFin": 126,
              "effShootPwr": 126,
              "effShootFine": 132,
              "effShootVol": 119,
              "effShootLdr": 127,
              "effShootFk": 84,
              "colorTags": [
                {
                  "fill": "#0073d5",
                  "border": "#e7c400"
                }
              ]
            }
          ],
          "id": "5xuf1on",
          "subfolders": []
        },
        {
          "name": "Fighters (Strikers and Wingers)",
          "open": false,
          "players": [
            {
              "name": "Endrick",
              "roles": [
                "ST",
                "Wing"
              ],
              "archetypePrimary": "Fighter",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 92,
                "baseSprint": 93,
                "baseAgility": 91,
                "heightCm": 173,
                "weight": 66,
                "strength": 82,
                "balance": 89,
                "accelType": "explosive",
                "buildType": "stocky",
                "activePS": [
                  "quickstep",
                  "rapid",
                  "technical_plus",
                  "low_driven_plus",
                  "finesse",
                  "trickster",
                  "first_touch",
                  "tiki_taka",
                  "power_shot",
                  "game_changer"
                ],
                "shortPass": 88,
                "longPass": 73,
                "vision": 84,
                "crossing": 60,
                "curve": 82,
                "fkAccuracy": 88,
                "standTackle": 40,
                "slideTackle": 41,
                "interceptions": 27,
                "headingAcc": 93,
                "defAwareness": 32,
                "aggression": 70,
                "jumping": 93,
                "finishing": 92,
                "shotPower": 91,
                "longShots": 87,
                "volleys": 85,
                "attPositioning": 92,
                "composure": 86,
                "reactions": 88,
                "ballControl": 90,
                "dribbling": 89,
                "stamina": 90
              },
              "effA": 120,
              "effS": 86,
              "effG": 122,
              "effT": 87,
              "effSlip": 128,
              "effPassShort": 104,
              "effPassLong": 78,
              "effPassThrough": 104,
              "effPassCross": 71,
              "effDefTackle": 43,
              "effDefPos": 36,
              "effDefInt": 30,
              "effDefAer": 95,
              "effDefBully": 70,
              "effDefSlide": 47,
              "effShootFin": 109,
              "effShootPwr": 107,
              "effShootFine": 113,
              "effShootVol": 98,
              "effShootLdr": 122,
              "effShootFk": 91,
              "colorTags": [
                {
                  "fill": "#c400c4",
                  "border": "#8600ff"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "Puskas",
              "roles": [
                "ST"
              ],
              "archetypePrimary": "Fighter",
              "archetypeSecondary": "Assassin",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 93,
                "baseSprint": 91,
                "baseAgility": 92,
                "heightCm": 172,
                "weight": 72,
                "strength": 80,
                "balance": 93,
                "accelType": "explosive",
                "buildType": "stocky",
                "activePS": [
                  "quickstep",
                  "rapid",
                  "first_touch",
                  "technical",
                  "trickster",
                  "incisive",
                  "finesse_plus",
                  "low_driven_plus",
                  "power_shot",
                  "game_changer"
                ],
                "shortPass": 92,
                "longPass": 90,
                "vision": 93,
                "crossing": 88,
                "curve": 92,
                "fkAccuracy": 90,
                "standTackle": 44,
                "slideTackle": 41,
                "interceptions": 47,
                "headingAcc": 80,
                "defAwareness": 45,
                "aggression": 63,
                "jumping": 74,
                "finishing": 97,
                "shotPower": 96,
                "longShots": 95,
                "volleys": 94,
                "attPositioning": 98,
                "composure": 97,
                "reactions": 97,
                "ballControl": 95,
                "dribbling": 92,
                "stamina": 94
              },
              "effA": 120,
              "effS": 84,
              "effG": 117,
              "effT": 91,
              "effSlip": 123,
              "effPassShort": 106,
              "effPassLong": 99,
              "effPassThrough": 124,
              "effPassCross": 104,
              "effDefTackle": 49,
              "effDefPos": 49,
              "effDefInt": 54,
              "effDefAer": 70,
              "effDefBully": 70,
              "effDefSlide": 49,
              "effShootFin": 122,
              "effShootPwr": 118,
              "effShootFine": 140,
              "effShootVol": 111,
              "effShootLdr": 129,
              "effShootFk": 97,
              "colorTags": [
                {
                  "fill": "#ced0d4",
                  "border": "#ffeb00"
                }
              ]
            },
            {
              "name": "Chawinga",
              "roles": [
                "ST",
                "Wing"
              ],
              "archetypePrimary": "Fighter",
              "archetypeSecondary": "Assassin",
              "state": {
                "chemStyle": null,
                "baseAccel": 96,
                "baseSprint": 97,
                "baseAgility": 94,
                "heightCm": 168,
                "weight": 62,
                "strength": 93,
                "balance": 93,
                "accelType": "controlled",
                "buildType": "normal",
                "activePS": [
                  "quickstep",
                  "rapid_plus",
                  "first_touch_plus",
                  "technical",
                  "press_proven",
                  "enforcer_plus",
                  "incisive",
                  "whipped",
                  "finesse",
                  "low_driven_plus"
                ],
                "shortPass": 96,
                "longPass": 93,
                "vision": 93,
                "crossing": 93,
                "curve": 90,
                "fkAccuracy": 80,
                "standTackle": 80,
                "slideTackle": 50,
                "interceptions": 61,
                "headingAcc": 84,
                "defAwareness": 50,
                "aggression": 86,
                "jumping": 94,
                "finishing": 96,
                "shotPower": 96,
                "longShots": 93,
                "volleys": 88,
                "attPositioning": 95,
                "composure": 94,
                "reactions": 96,
                "ballControl": 96,
                "dribbling": 96,
                "stamina": 93
              },
              "effA": 113,
              "effS": 97,
              "effG": 110,
              "effT": 95,
              "effSlip": 129,
              "effPassShort": 103,
              "effPassLong": 96,
              "effPassThrough": 118,
              "effPassCross": 107,
              "effDefTackle": 82,
              "effDefPos": 53,
              "effDefInt": 67,
              "effDefAer": 85,
              "effDefBully": 85,
              "effDefSlide": 61,
              "effShootFin": 112,
              "effShootPwr": 105,
              "effShootFine": 119,
              "effShootVol": 101,
              "effShootLdr": 123,
              "effShootFk": 85,
              "colorTags": [
                {
                  "fill": "#0073d5",
                  "border": "#e7c400"
                }
              ]
            }
          ],
          "id": "eu14hoh",
          "subfolders": []
        },
        {
          "name": "Striders/Junglers (Wingers and Strikers)",
          "open": true,
          "players": [
            {
              "name": "Rafael Leao",
              "roles": [
                "ST",
                "Wing"
              ],
              "archetypePrimary": "Jungler",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 95,
                "baseSprint": 95,
                "baseAgility": 99,
                "heightCm": 188,
                "weight": 81,
                "strength": 93,
                "balance": 99,
                "accelType": "controlled",
                "buildType": "normal",
                "activePS": [
                  "quickstep_plus",
                  "technical",
                  "rapid_plus",
                  "first_time",
                  "first_touch",
                  "trickster",
                  "incisive",
                  "tiki_taka",
                  "finesse_plus",
                  "intercept_ps",
                  "game_changer"
                ],
                "shortPass": 95,
                "longPass": 77,
                "vision": 94,
                "crossing": 92,
                "curve": 98,
                "fkAccuracy": 72,
                "standTackle": 34,
                "slideTackle": 29,
                "interceptions": 34,
                "headingAcc": 99,
                "defAwareness": 30,
                "aggression": 92,
                "jumping": 95,
                "finishing": 94,
                "shotPower": 95,
                "longShots": 93,
                "volleys": 93,
                "attPositioning": 94,
                "composure": 93,
                "reactions": 93,
                "ballControl": 93,
                "dribbling": 93,
                "stamina": 92
              },
              "effA": 109,
              "effS": 101,
              "effG": 111,
              "effT": 92,
              "effSlip": 103,
              "effPassShort": 111,
              "effPassLong": 86,
              "effPassThrough": 125,
              "effPassCross": 109,
              "effDefTackle": 37,
              "effDefPos": 33,
              "effDefInt": 47,
              "effDefAer": 109,
              "effDefBully": 76,
              "effDefSlide": 42,
              "effShootFin": 116,
              "effShootPwr": 109,
              "effShootFine": 137,
              "effShootVol": 118,
              "effShootLdr": 102,
              "effShootFk": 82,
              "colorTags": [
                {
                  "fill": "#b1006d",
                  "border": "#ff00e5"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "Thierry Henry",
              "roles": [
                "ST"
              ],
              "archetypePrimary": "Jungler",
              "archetypeSecondary": "Freight Train",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 95,
                "baseSprint": 96,
                "baseAgility": 91,
                "heightCm": 188,
                "weight": 83,
                "strength": 88,
                "balance": 88,
                "accelType": "controlled",
                "buildType": "normal",
                "activePS": [
                  "quickstep_plus",
                  "rapid",
                  "technical",
                  "first_touch",
                  "trickster",
                  "tiki_taka_plus",
                  "outside_foot",
                  "finesse_plus",
                  "low_driven",
                  "game_changer"
                ],
                "shortPass": 92,
                "longPass": 80,
                "vision": 85,
                "crossing": 85,
                "curve": 96,
                "fkAccuracy": 91,
                "standTackle": 58,
                "slideTackle": 51,
                "interceptions": 60,
                "headingAcc": 94,
                "defAwareness": 52,
                "aggression": 70,
                "jumping": 75,
                "finishing": 98,
                "shotPower": 92,
                "longShots": 91,
                "volleys": 93,
                "attPositioning": 96,
                "composure": 90,
                "reactions": 94,
                "ballControl": 95,
                "dribbling": 94,
                "stamina": 93
              },
              "effA": 106,
              "effS": 102,
              "effG": 103,
              "effT": 89,
              "effSlip": 94,
              "effPassShort": 111,
              "effPassLong": 89,
              "effPassThrough": 112,
              "effPassCross": 102,
              "effDefTackle": 63,
              "effDefPos": 54,
              "effDefInt": 66,
              "effDefAer": 89,
              "effDefBully": 79,
              "effDefSlide": 56,
              "effShootFin": 120,
              "effShootPwr": 104,
              "effShootFine": 135,
              "effShootVol": 106,
              "effShootLdr": 113,
              "effShootFk": 99,
              "colorTags": [
                {
                  "fill": "#4a3500",
                  "border": "#ffe900"
                }
              ]
            },
            {
              "name": "Mbappe",
              "roles": [
                "ST",
                "Wing"
              ],
              "archetypePrimary": "Jungler",
              "archetypeSecondary": "Assassin",
              "state": {
                "chemStyle": "basic",
                "baseAccel": 99,
                "baseSprint": 99,
                "baseAgility": 97,
                "heightCm": 182,
                "weight": 75,
                "strength": 82,
                "balance": 93,
                "accelType": "explosive",
                "buildType": "normal",
                "activePS": [
                  "technical",
                  "first_touch",
                  "trickster",
                  "finesse_plus",
                  "game_changer",
                  "quickstep",
                  "rapid_plus",
                  "tiki_taka",
                  "incisive",
                  "low_driven_plus"
                ],
                "shortPass": 92,
                "longPass": 81,
                "vision": 88,
                "crossing": 83,
                "curve": 85,
                "fkAccuracy": 74,
                "standTackle": 54,
                "slideTackle": 51,
                "interceptions": 61,
                "headingAcc": 95,
                "defAwareness": 41,
                "aggression": 71,
                "jumping": 94,
                "finishing": 98,
                "shotPower": 97,
                "longShots": 95,
                "volleys": 94,
                "attPositioning": 97,
                "composure": 94,
                "reactions": 96,
                "ballControl": 97,
                "dribbling": 97,
                "stamina": 91
              },
              "effA": 124,
              "effS": 91,
              "effG": 121,
              "effT": 85,
              "effSlip": 116,
              "effPassShort": 112,
              "effPassLong": 92,
              "effPassThrough": 121,
              "effPassCross": 93,
              "effDefTackle": 61,
              "effDefPos": 48,
              "effDefInt": 67,
              "effDefAer": 102,
              "effDefBully": 77,
              "effDefSlide": 62,
              "effShootFin": 121,
              "effShootPwr": 111,
              "effShootFine": 128,
              "effShootVol": 110,
              "effShootLdr": 122,
              "effShootFk": 83,
              "colorTags": [
                {
                  "fill": "#0073d5",
                  "border": "#e7c400"
                }
              ]
            },
            {
              "name": "Dembele",
              "roles": [
                "ST",
                "Wing"
              ],
              "archetypePrimary": "Jungler",
              "archetypeSecondary": "Assassin",
              "state": {
                "chemStyle": "marksman",
                "baseAccel": 96,
                "baseSprint": 97,
                "baseAgility": 97,
                "heightCm": 178,
                "weight": 67,
                "strength": 76,
                "balance": 91,
                "accelType": "explosive",
                "buildType": "lean",
                "activePS": [
                  "technical",
                  "trickster",
                  "finesse_plus",
                  "tiki_taka",
                  "incisive",
                  "rapid",
                  "quickstep_plus",
                  "pinged",
                  "outside_foot",
                  "low_driven"
                ],
                "shortPass": 97,
                "longPass": 85,
                "vision": 91,
                "crossing": 86,
                "curve": 92,
                "fkAccuracy": 73,
                "standTackle": 60,
                "slideTackle": 47,
                "interceptions": 53,
                "headingAcc": 90,
                "defAwareness": 60,
                "aggression": 70,
                "jumping": 91,
                "finishing": 94,
                "shotPower": 95,
                "longShots": 90,
                "volleys": 93,
                "attPositioning": 98,
                "composure": 91,
                "reactions": 94,
                "ballControl": 97,
                "dribbling": 97,
                "stamina": 93
              },
              "effA": 127,
              "effS": 89,
              "effG": 118,
              "effT": 75,
              "effSlip": 112,
              "effPassShort": 115,
              "effPassLong": 101,
              "effPassThrough": 125,
              "effPassCross": 97,
              "effDefTackle": 64,
              "effDefPos": 64,
              "effDefInt": 61,
              "effDefAer": 100,
              "effDefBully": 70,
              "effDefSlide": 54,
              "effShootFin": 117,
              "effShootPwr": 108,
              "effShootFine": 133,
              "effShootVol": 110,
              "effShootLdr": 117,
              "effShootFk": 83,
              "colorTags": [
                {
                  "fill": "#0073d5",
                  "border": "#e7c400"
                }
              ]
            }
          ],
          "id": "612a4d0",
          "subfolders": []
        },
        {
          "id": "jhw6fbu",
          "name": "Assassins (Wingers and Playmakers)",
          "open": false,
          "players": [
            {
              "name": "Pina",
              "roles": [
                "ST",
                "CAM",
                "Wing"
              ],
              "archetypePrimary": "Assassin",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 94,
                "baseSprint": 94,
                "baseAgility": 92,
                "heightCm": 160,
                "weight": 63,
                "strength": 72,
                "balance": 88,
                "accelType": "explosive",
                "buildType": "normal",
                "activePS": [
                  "technical_plus",
                  "rapid_plus",
                  "quickstep",
                  "low_driven",
                  "finesse",
                  "incisive",
                  "tiki_taka",
                  "trickster",
                  "game_changer",
                  "dead_ball"
                ],
                "shortPass": 90,
                "longPass": 79,
                "vision": 88,
                "crossing": 88,
                "curve": 85,
                "fkAccuracy": 89,
                "standTackle": 58,
                "slideTackle": 54,
                "interceptions": 40,
                "headingAcc": 73,
                "defAwareness": 34,
                "aggression": 72,
                "jumping": 74,
                "finishing": 90,
                "shotPower": 87,
                "longShots": 94,
                "volleys": 91,
                "attPositioning": 91,
                "composure": 89,
                "reactions": 88,
                "ballControl": 91,
                "dribbling": 91,
                "stamina": 90
              },
              "effA": 130,
              "effS": 85,
              "effG": 131,
              "effT": 81,
              "effSlip": 147,
              "effPassShort": 107,
              "effPassLong": 79,
              "effPassThrough": 119,
              "effPassCross": 95,
              "effDefTackle": 57,
              "effDefPos": 39,
              "effDefInt": 43,
              "effDefAer": 52,
              "effDefBully": 69,
              "effDefSlide": 62,
              "effShootFin": 111,
              "effShootPwr": 94,
              "effShootFine": 124,
              "effShootVol": 107,
              "effShootLdr": 110,
              "effShootFk": 107,
              "colorTags": [
                {
                  "fill": "#0058ff",
                  "border": "#00caff"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "Debinha",
              "roles": [
                "CAM",
                "Wing"
              ],
              "archetypePrimary": "Assassin",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 93,
                "baseSprint": 92,
                "baseAgility": 94,
                "heightCm": 155,
                "weight": 52,
                "strength": 70,
                "balance": 94,
                "accelType": "explosive",
                "buildType": "normal",
                "activePS": [
                  "quickstep_plus",
                  "rapid",
                  "technical",
                  "first_touch",
                  "first_time",
                  "low_driven",
                  "incisive",
                  "game_changer",
                  "finesse_plus",
                  "trickster_plus"
                ],
                "shortPass": 92,
                "longPass": 92,
                "vision": 92,
                "crossing": 90,
                "curve": 92,
                "fkAccuracy": 87,
                "standTackle": 39,
                "slideTackle": 44,
                "interceptions": 49,
                "headingAcc": 56,
                "defAwareness": 49,
                "aggression": 70,
                "jumping": 75,
                "finishing": 93,
                "shotPower": 92,
                "longShots": 90,
                "volleys": 90,
                "attPositioning": 92,
                "composure": 92,
                "reactions": 92,
                "ballControl": 95,
                "dribbling": 95,
                "stamina": 90
              },
              "effA": 137,
              "effS": 84,
              "effG": 131,
              "effT": 77,
              "effSlip": 149,
              "effPassShort": 105,
              "effPassLong": 92,
              "effPassThrough": 124,
              "effPassCross": 97,
              "effDefTackle": 38,
              "effDefPos": 54,
              "effDefInt": 54,
              "effDefAer": 39,
              "effDefBully": 56,
              "effDefSlide": 52,
              "effShootFin": 118,
              "effShootPwr": 102,
              "effShootFine": 139,
              "effShootVol": 118,
              "effShootLdr": 116,
              "effShootFk": 94,
              "colorTags": [
                {
                  "fill": "#4a3500",
                  "border": "#ffe900"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "Karchaoui",
              "roles": [
                "CAM",
                "Wing"
              ],
              "archetypePrimary": "Assassin",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 95,
                "baseSprint": 91,
                "baseAgility": 94,
                "heightCm": 160,
                "weight": 55,
                "strength": 63,
                "balance": 89,
                "accelType": "explosive",
                "buildType": "normal",
                "activePS": [
                  "rapid_plus",
                  "technical_plus",
                  "quickstep",
                  "first_touch",
                  "trickster",
                  "whipped",
                  "pinged",
                  "tiki_taka",
                  "incisive",
                  "finesse"
                ],
                "shortPass": 93,
                "longPass": 91,
                "vision": 92,
                "crossing": 91,
                "curve": 86,
                "fkAccuracy": 80,
                "standTackle": 89,
                "slideTackle": 85,
                "interceptions": 92,
                "headingAcc": 73,
                "defAwareness": 85,
                "aggression": 78,
                "jumping": 83,
                "finishing": 82,
                "shotPower": 93,
                "longShots": 86,
                "volleys": 64,
                "attPositioning": 90,
                "composure": 92,
                "reactions": 91,
                "ballControl": 92,
                "dribbling": 93,
                "stamina": 98
              },
              "effA": 136,
              "effS": 83,
              "effG": 134,
              "effT": 74,
              "effSlip": 148,
              "effPassShort": 111,
              "effPassLong": 101,
              "effPassThrough": 125,
              "effPassCross": 107,
              "effDefTackle": 88,
              "effDefPos": 94,
              "effDefInt": 96,
              "effDefAer": 60,
              "effDefBully": 78,
              "effDefSlide": 96,
              "effShootFin": 100,
              "effShootPwr": 102,
              "effShootFine": 123,
              "effShootVol": 82,
              "effShootLdr": 101,
              "effShootFk": 85,
              "colorTags": [
                {
                  "fill": "#dfddeb",
                  "border": "#ca6262"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "V.Lopez",
              "roles": [
                "CAM",
                "Wing"
              ],
              "archetypePrimary": "Assassin",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "maestro",
                "baseAccel": 99,
                "baseSprint": 99,
                "baseAgility": 99,
                "heightCm": 160,
                "weight": 53,
                "strength": 76,
                "balance": 98,
                "accelType": "explosive",
                "buildType": "lean",
                "activePS": [
                  "quickstep",
                  "rapid",
                  "technical_plus",
                  "first_touch",
                  "trickster",
                  "low_driven",
                  "pinged",
                  "tiki_taka",
                  "outside_foot",
                  "incisive_plus",
                  "finesse_plus"
                ],
                "shortPass": 98,
                "longPass": 93,
                "vision": 98,
                "crossing": 90,
                "curve": 96,
                "fkAccuracy": 88,
                "standTackle": 69,
                "slideTackle": 52,
                "interceptions": 58,
                "headingAcc": 76,
                "defAwareness": 61,
                "aggression": 71,
                "jumping": 92,
                "finishing": 96,
                "shotPower": 94,
                "longShots": 94,
                "volleys": 93,
                "attPositioning": 98,
                "composure": 96,
                "reactions": 96,
                "ballControl": 97,
                "dribbling": 97,
                "stamina": 96
              },
              "effA": 134,
              "effS": 88,
              "effG": 132,
              "effT": 73,
              "effSlip": 148,
              "effPassShort": 119,
              "effPassLong": 109,
              "effPassThrough": 143,
              "effPassCross": 96,
              "effDefTackle": 70,
              "effDefPos": 66,
              "effDefInt": 66,
              "effDefAer": 70,
              "effDefBully": 65,
              "effDefSlide": 62,
              "effShootFin": 122,
              "effShootPwr": 109,
              "effShootFine": 147,
              "effShootVol": 117,
              "effShootLdr": 124,
              "effShootFk": 101,
              "colorTags": [
                {
                  "fill": "#0096b1",
                  "border": "#004a8c"
                }
              ]
            },
            {
              "name": "Messi",
              "roles": [
                "ST",
                "CAM",
                "Wing"
              ],
              "archetypePrimary": "Assassin",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "engine",
                "baseAccel": 92,
                "baseSprint": 92,
                "baseAgility": 91,
                "heightCm": 169,
                "weight": 67,
                "strength": 68,
                "balance": 89,
                "accelType": "explosive",
                "buildType": "normal",
                "activePS": [
                  "quickstep",
                  "rapid_plus",
                  "technical_plus",
                  "trickster",
                  "tiki_taka_plus",
                  "incisive",
                  "finesse",
                  "dead_ball",
                  "low_driven",
                  "game_changer"
                ],
                "shortPass": 90,
                "longPass": 90,
                "vision": 91,
                "crossing": 88,
                "curve": 95,
                "fkAccuracy": 93,
                "standTackle": 35,
                "slideTackle": 24,
                "interceptions": 40,
                "headingAcc": 85,
                "defAwareness": 20,
                "aggression": 69,
                "jumping": 70,
                "finishing": 94,
                "shotPower": 91,
                "longShots": 91,
                "volleys": 89,
                "attPositioning": 92,
                "composure": 92,
                "reactions": 93,
                "ballControl": 94,
                "dribbling": 90,
                "stamina": 85
              },
              "effA": 126,
              "effS": 84,
              "effG": 128,
              "effT": 79,
              "effSlip": 134,
              "effPassShort": 115,
              "effPassLong": 96,
              "effPassThrough": 126,
              "effPassCross": 101,
              "effDefTackle": 38,
              "effDefPos": 24,
              "effDefInt": 45,
              "effDefAer": 67,
              "effDefBully": 54,
              "effDefSlide": 32,
              "effShootFin": 115,
              "effShootPwr": 102,
              "effShootFine": 131,
              "effShootVol": 105,
              "effShootLdr": 112,
              "effShootFk": 112,
              "colorTags": [
                {
                  "fill": "#dfddeb",
                  "border": "#ca6262"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            }
          ],
          "subfolders": []
        }
      ]
    },
    {
      "id": "c61z8tb",
      "name": "Defenders",
      "open": false,
      "players": [],
      "subfolders": [
        {
          "name": "Neutralists (Generalist Center-mid)",
          "open": true,
          "players": [
            {
              "name": "Joelinton",
              "roles": [
                "CDM"
              ],
              "archetypePrimary": "Bruiser",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 91,
                "baseSprint": 91,
                "baseAgility": 89,
                "heightCm": 186,
                "weight": 81,
                "strength": 96,
                "balance": 90,
                "accelType": "lengthy",
                "buildType": "stocky",
                "activePS": [
                  "quickstep",
                  "technical",
                  "bruiser",
                  "relentless",
                  "incisive_plus",
                  "pinged_plus",
                  "tiki_taka",
                  "intercept_ps_plus",
                  "anticipate",
                  "jockey",
                  "finesse"
                ],
                "shortPass": 95,
                "longPass": 90,
                "vision": 93,
                "crossing": 92,
                "curve": 92,
                "fkAccuracy": 87,
                "standTackle": 91,
                "slideTackle": 84,
                "interceptions": 91,
                "headingAcc": 90,
                "defAwareness": 91,
                "aggression": 97,
                "jumping": 96,
                "finishing": 90,
                "shotPower": 99,
                "longShots": 92,
                "volleys": 88,
                "attPositioning": 91,
                "composure": 92,
                "reactions": 91,
                "ballControl": 93,
                "dribbling": 91,
                "stamina": 95
              },
              "effA": 84,
              "effS": 114,
              "effG": 86,
              "effT": 94,
              "effSlip": 77,
              "effPassShort": 106,
              "effPassLong": 111,
              "effPassThrough": 124,
              "effPassCross": 101,
              "effDefTackle": 110,
              "effDefPos": 109,
              "effDefInt": 115,
              "effDefAer": 107,
              "effDefBully": 116,
              "effDefSlide": 106,
              "effShootFin": 103,
              "effShootPwr": 109,
              "effShootFine": 117,
              "effShootVol": 97,
              "effShootLdr": 101,
              "effShootFk": 91,
              "colorTags": [
                {
                  "fill": "#dfddeb",
                  "border": "#ca6262"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "Stiller TOTS",
              "roles": [
                "CDM"
              ],
              "archetypePrimary": "Fighter",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "anchor",
                "baseAccel": 90,
                "baseSprint": 90,
                "baseAgility": 94,
                "heightCm": 183,
                "weight": 77,
                "strength": 87,
                "balance": 94,
                "accelType": "controlled",
                "buildType": "normal",
                "activePS": [
                  "technical",
                  "first_touch",
                  "press_proven",
                  "incisive",
                  "pinged_plus",
                  "tiki_taka_plus",
                  "long_ball",
                  "intercept_ps_plus",
                  "anticipate",
                  "jockey"
                ],
                "shortPass": 96,
                "longPass": 94,
                "vision": 95,
                "crossing": 92,
                "curve": 85,
                "fkAccuracy": 85,
                "standTackle": 94,
                "slideTackle": 90,
                "interceptions": 96,
                "headingAcc": 86,
                "defAwareness": 95,
                "aggression": 91,
                "jumping": 92,
                "finishing": 75,
                "shotPower": 90,
                "longShots": 86,
                "volleys": 71,
                "attPositioning": 83,
                "composure": 96,
                "reactions": 96,
                "ballControl": 95,
                "dribbling": 94,
                "stamina": 93
              },
              "effA": 91,
              "effS": 93,
              "effG": 99,
              "effT": 91,
              "effSlip": 98,
              "effPassShort": 113,
              "effPassLong": 120,
              "effPassThrough": 127,
              "effPassCross": 101,
              "effDefTackle": 111,
              "effDefPos": 114,
              "effDefInt": 120,
              "effDefAer": 103,
              "effDefBully": 106,
              "effDefSlide": 109,
              "effShootFin": 91,
              "effShootPwr": 102,
              "effShootFine": 101,
              "effShootVol": 83,
              "effShootLdr": 92,
              "effShootFk": 86,
              "colorTags": [
                {
                  "fill": "#0073d5",
                  "border": "#e7c400"
                }
              ]
            },
            {
              "name": "Mainoo",
              "roles": [
                "CDM"
              ],
              "archetypePrimary": "Bruiser",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 88,
                "baseSprint": 84,
                "baseAgility": 90,
                "heightCm": 181,
                "weight": 80,
                "strength": 85,
                "balance": 97,
                "accelType": "controlled",
                "buildType": "normal",
                "activePS": [
                  "quickstep",
                  "technical",
                  "bruiser",
                  "rapid",
                  "first_touch",
                  "relentless",
                  "incisive",
                  "intercept_ps_plus",
                  "anticipate",
                  "tiki_taka_plus",
                  "pinged_plus"
                ],
                "shortPass": 95,
                "longPass": 94,
                "vision": 91,
                "crossing": 80,
                "curve": 91,
                "fkAccuracy": 68,
                "standTackle": 88,
                "slideTackle": 85,
                "interceptions": 84,
                "headingAcc": 73,
                "defAwareness": 80,
                "aggression": 86,
                "jumping": 86,
                "finishing": 90,
                "shotPower": 85,
                "longShots": 80,
                "volleys": 72,
                "attPositioning": 91,
                "composure": 91,
                "reactions": 88,
                "ballControl": 90,
                "dribbling": 91,
                "stamina": 86
              },
              "effA": 100,
              "effS": 91,
              "effG": 97,
              "effT": 89,
              "effSlip": 95,
              "effPassShort": 110,
              "effPassLong": 114,
              "effPassThrough": 116,
              "effPassCross": 88,
              "effDefTackle": 106,
              "effDefPos": 88,
              "effDefInt": 105,
              "effDefAer": 87,
              "effDefBully": 104,
              "effDefSlide": 103,
              "effShootFin": 104,
              "effShootPwr": 96,
              "effShootFine": 103,
              "effShootVol": 83,
              "effShootLdr": 94,
              "effShootFk": 71,
              "colorTags": [
                {
                  "fill": "#c400c4",
                  "border": "#8600ff"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "Declan Rice",
              "roles": [
                "CDM"
              ],
              "archetypePrimary": "Bruiser",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 90,
                "baseSprint": 90,
                "baseAgility": 90,
                "heightCm": 185,
                "weight": 80,
                "strength": 92,
                "balance": 90,
                "accelType": "controlled",
                "buildType": "normal",
                "activePS": [
                  "press_proven",
                  "relentless",
                  "aerial",
                  "incisive",
                  "pinged_plus",
                  "whipped",
                  "block",
                  "anticipate_plus",
                  "intercept_ps_plus",
                  "dead_ball"
                ],
                "shortPass": 95,
                "longPass": 95,
                "vision": 93,
                "crossing": 88,
                "curve": 86,
                "fkAccuracy": 75,
                "standTackle": 93,
                "slideTackle": 93,
                "interceptions": 95,
                "headingAcc": 93,
                "defAwareness": 93,
                "aggression": 92,
                "jumping": 92,
                "finishing": 64,
                "shotPower": 92,
                "longShots": 92,
                "volleys": 50,
                "attPositioning": 77,
                "composure": 92,
                "reactions": 92,
                "ballControl": 84,
                "dribbling": 82,
                "stamina": 92
              },
              "effA": 92,
              "effS": 96,
              "effG": 88,
              "effT": 90,
              "effSlip": 80,
              "effPassShort": 101,
              "effPassLong": 116,
              "effPassThrough": 114,
              "effPassCross": 104,
              "effDefTackle": 115,
              "effDefPos": 111,
              "effDefInt": 118,
              "effDefAer": 114,
              "effDefBully": 108,
              "effDefSlide": 109,
              "effShootFin": 76,
              "effShootPwr": 102,
              "effShootFine": 102,
              "effShootVol": 59,
              "effShootLdr": 87,
              "effShootFk": 92,
              "colorTags": [
                {
                  "fill": "#be0063",
                  "border": "#ff009d"
                },
                {
                  "fill": "#008400",
                  "border": "#00ff00"
                }
              ]
            }
          ],
          "id": "vkkivoz",
          "subfolders": []
        },
        {
          "name": "Bruisers (Generalist Fullbacks)",
          "open": false,
          "players": [
            {
              "name": "Cancelo",
              "roles": [
                "FB"
              ],
              "archetypePrimary": "Bruiser",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 94,
                "baseSprint": 88,
                "baseAgility": 86,
                "heightCm": 182,
                "weight": 74,
                "strength": 99,
                "balance": 85,
                "accelType": "controlled",
                "buildType": "normal",
                "activePS": [
                  "quickstep",
                  "technical",
                  "bruiser",
                  "first_touch",
                  "relentless",
                  "tiki_taka_plus",
                  "whipped",
                  "outside_foot",
                  "intercept_ps",
                  "block",
                  "jockey_plus"
                ],
                "shortPass": 93,
                "longPass": 86,
                "vision": 92,
                "crossing": 93,
                "curve": 94,
                "fkAccuracy": 75,
                "standTackle": 92,
                "slideTackle": 88,
                "interceptions": 90,
                "headingAcc": 83,
                "defAwareness": 86,
                "aggression": 99,
                "jumping": 99,
                "finishing": 77,
                "shotPower": 88,
                "longShots": 87,
                "volleys": 71,
                "attPositioning": 89,
                "composure": 92,
                "reactions": 91,
                "ballControl": 93,
                "dribbling": 92,
                "stamina": 99
              },
              "effA": 101,
              "effS": 96,
              "effG": 90,
              "effT": 85,
              "effSlip": 85,
              "effPassShort": 109,
              "effPassLong": 92,
              "effPassThrough": 112,
              "effPassCross": 110,
              "effDefTackle": 100,
              "effDefPos": 114,
              "effDefInt": 105,
              "effDefAer": 104,
              "effDefBully": 116,
              "effDefSlide": 110,
              "effShootFin": 90,
              "effShootPwr": 96,
              "effShootFine": 110,
              "effShootVol": 82,
              "effShootLdr": 92,
              "effShootFk": 79,
              "colorTags": [
                {
                  "fill": "#d29fff",
                  "border": "#a74cff"
                }
              ]
            },
            {
              "name": "Thuram",
              "roles": [
                "FB"
              ],
              "archetypePrimary": "Bruiser",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 90,
                "baseSprint": 90,
                "baseAgility": 86,
                "heightCm": 182,
                "weight": 75,
                "strength": 93,
                "balance": 90,
                "accelType": "controlled",
                "buildType": "normal",
                "activePS": [
                  "quickstep",
                  "bruiser",
                  "rapid_plus",
                  "whipped",
                  "jockey_plus",
                  "block",
                  "anticipate",
                  "slide_tackle_ps",
                  "aerial"
                ],
                "shortPass": 90,
                "longPass": 85,
                "vision": 81,
                "crossing": 85,
                "curve": 83,
                "fkAccuracy": 46,
                "standTackle": 87,
                "slideTackle": 93,
                "interceptions": 87,
                "headingAcc": 86,
                "defAwareness": 91,
                "aggression": 93,
                "jumping": 90,
                "finishing": 60,
                "shotPower": 65,
                "longShots": 61,
                "volleys": 57,
                "attPositioning": 70,
                "composure": 90,
                "reactions": 90,
                "ballControl": 84,
                "dribbling": 86,
                "stamina": 92
              },
              "effA": 102,
              "effS": 98,
              "effG": 89,
              "effT": 86,
              "effSlip": 80,
              "effPassShort": 95,
              "effPassLong": 90,
              "effPassThrough": 93,
              "effPassCross": 100,
              "effDefTackle": 101,
              "effDefPos": 121,
              "effDefInt": 94,
              "effDefAer": 107,
              "effDefBully": 111,
              "effDefSlide": 117,
              "effShootFin": 71,
              "effShootPwr": 74,
              "effShootFine": 82,
              "effShootVol": 66,
              "effShootLdr": 72,
              "effShootFk": 52,
              "colorTags": [
                {
                  "fill": "#4a3500",
                  "border": "#ffe900"
                }
              ]
            },
            {
              "name": "Theo Hernandez",
              "roles": [
                "FB"
              ],
              "archetypePrimary": "Bruiser",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 91,
                "baseSprint": 92,
                "baseAgility": 92,
                "heightCm": 184,
                "weight": 81,
                "strength": 85,
                "balance": 92,
                "accelType": "controlled",
                "buildType": "normal",
                "activePS": [
                  "quickstep",
                  "bruiser_plus",
                  "rapid",
                  "incisive",
                  "pinged",
                  "tiki_taka",
                  "intercept_ps",
                  "block",
                  "anticipate",
                  "power_shot_plus",
                  "dead_ball"
                ],
                "shortPass": 92,
                "longPass": 90,
                "vision": 85,
                "crossing": 90,
                "curve": 92,
                "fkAccuracy": 91,
                "standTackle": 90,
                "slideTackle": 90,
                "interceptions": 90,
                "headingAcc": 76,
                "defAwareness": 87,
                "aggression": 90,
                "jumping": 90,
                "finishing": 88,
                "shotPower": 95,
                "longShots": 91,
                "volleys": 88,
                "attPositioning": 88,
                "composure": 84,
                "reactions": 97,
                "ballControl": 92,
                "dribbling": 87,
                "stamina": 90
              },
              "effA": 101,
              "effS": 99,
              "effG": 94,
              "effT": 88,
              "effSlip": 84,
              "effPassShort": 102,
              "effPassLong": 103,
              "effPassThrough": 109,
              "effPassCross": 99,
              "effDefTackle": 105,
              "effDefPos": 104,
              "effDefInt": 108,
              "effDefAer": 93,
              "effDefBully": 113,
              "effDefSlide": 108,
              "effShootFin": 99,
              "effShootPwr": 117,
              "effShootFine": 105,
              "effShootVol": 95,
              "effShootLdr": 101,
              "effShootFk": 106,
              "colorTags": [
                {
                  "fill": "#fece00",
                  "border": "#ffe900"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            }
          ],
          "id": "oobs6ri",
          "subfolders": []
        },
        {
          "name": "Titans (Centerbacks)",
          "open": false,
          "players": [
            {
              "name": "Campbell",
              "roles": [
                "CB"
              ],
              "archetypePrimary": "Brawler",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 91,
                "baseSprint": 92,
                "baseAgility": 88,
                "heightCm": 188,
                "weight": 90,
                "strength": 94,
                "balance": 87,
                "accelType": "lengthy",
                "buildType": "very_stocky",
                "activePS": [
                  "quickstep",
                  "bruiser_plus",
                  "intercept_ps_plus",
                  "jockey",
                  "block",
                  "aerial",
                  "pinged",
                  "precision_header",
                  "slide_tackle_ps",
                  "anticipate_plus"
                ],
                "shortPass": 90,
                "longPass": 90,
                "vision": 75,
                "crossing": 55,
                "curve": 40,
                "fkAccuracy": 32,
                "standTackle": 94,
                "slideTackle": 92,
                "interceptions": 93,
                "headingAcc": 91,
                "defAwareness": 93,
                "aggression": 92,
                "jumping": 91,
                "finishing": 41,
                "shotPower": 59,
                "longShots": 39,
                "volleys": 39,
                "attPositioning": 33,
                "composure": 93,
                "reactions": 93,
                "ballControl": 92,
                "dribbling": 87,
                "stamina": 90
              },
              "effA": 79,
              "effS": 114,
              "effG": 78,
              "effT": 106,
              "effSlip": 68,
              "effPassShort": 94,
              "effPassLong": 102,
              "effPassThrough": 87,
              "effPassCross": 59,
              "effDefTackle": 128,
              "effDefPos": 118,
              "effDefInt": 118,
              "effDefAer": 126,
              "effDefBully": 135,
              "effDefSlide": 119,
              "effShootFin": 52,
              "effShootPwr": 73,
              "effShootFine": 45,
              "effShootVol": 48,
              "effShootLdr": 66,
              "effShootFk": 36,
              "colorTags": [
                {
                  "fill": "#4a3500",
                  "border": "#ffe900"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "Zagadou",
              "roles": [
                "CB"
              ],
              "archetypePrimary": "Wall",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 87,
                "baseSprint": 88,
                "baseAgility": 75,
                "heightCm": 196,
                "weight": 90,
                "strength": 95,
                "balance": 80,
                "accelType": "lengthy",
                "buildType": "stocky",
                "activePS": [
                  "anticipate_plus",
                  "intercept_ps_plus",
                  "block",
                  "power_shot",
                  "bruiser",
                  "aerial",
                  "jockey",
                  "pinged",
                  "quickstep",
                  "slide_tackle_ps"
                ],
                "shortPass": 90,
                "longPass": 85,
                "vision": 70,
                "crossing": 54,
                "curve": 43,
                "fkAccuracy": 29,
                "standTackle": 92,
                "slideTackle": 92,
                "interceptions": 93,
                "headingAcc": 95,
                "defAwareness": 96,
                "aggression": 85,
                "jumping": 90,
                "finishing": 33,
                "shotPower": 83,
                "longShots": 32,
                "volleys": 32,
                "attPositioning": 39,
                "composure": 91,
                "reactions": 95,
                "ballControl": 75,
                "dribbling": 75,
                "stamina": 90
              },
              "effA": 76,
              "effS": 112,
              "effG": 60,
              "effT": 92,
              "effSlip": 38,
              "effPassShort": 96,
              "effPassLong": 99,
              "effPassThrough": 86,
              "effPassCross": 60,
              "effDefTackle": 125,
              "effDefPos": 122,
              "effDefInt": 118,
              "effDefAer": 121,
              "effDefBully": 123,
              "effDefSlide": 116,
              "effShootFin": 43,
              "effShootPwr": 103,
              "effShootFine": 44,
              "effShootVol": 39,
              "effShootLdr": 72,
              "effShootFk": 34,
              "colorTags": [
                {
                  "fill": "#4a3500",
                  "border": "#ffe900"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            },
            {
              "name": "Saliba",
              "roles": [
                "CB"
              ],
              "archetypePrimary": "Spider",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 89,
                "baseSprint": 88,
                "baseAgility": 84,
                "heightCm": 193,
                "weight": 85,
                "strength": 94,
                "balance": 83,
                "accelType": "lengthy",
                "buildType": "normal",
                "activePS": [
                  "anticipate_plus",
                  "intercept_ps_plus",
                  "block",
                  "jockey",
                  "quickstep",
                  "slide_tackle_ps",
                  "bruiser_plus",
                  "relentless",
                  "long_ball",
                  "precision_header"
                ],
                "shortPass": 94,
                "longPass": 91,
                "vision": 73,
                "crossing": 68,
                "curve": 65,
                "fkAccuracy": 43,
                "standTackle": 94,
                "slideTackle": 98,
                "interceptions": 95,
                "headingAcc": 90,
                "defAwareness": 95,
                "aggression": 92,
                "jumping": 95,
                "finishing": 47,
                "shotPower": 80,
                "longShots": 31,
                "volleys": 45,
                "attPositioning": 72,
                "composure": 94,
                "reactions": 94,
                "ballControl": 85,
                "dribbling": 84,
                "stamina": 87
              },
              "effA": 82,
              "effS": 112,
              "effG": 73,
              "effT": 86,
              "effSlip": 53,
              "effPassShort": 101,
              "effPassLong": 102,
              "effPassThrough": 96,
              "effPassCross": 75,
              "effDefTackle": 122,
              "effDefPos": 120,
              "effDefInt": 120,
              "effDefAer": 120,
              "effDefBully": 124,
              "effDefSlide": 119,
              "effShootFin": 58,
              "effShootPwr": 92,
              "effShootFine": 56,
              "effShootVol": 53,
              "effShootLdr": 71,
              "effShootFk": 48,
              "colorTags": [
                {
                  "fill": "#0073d5",
                  "border": "#e7c400"
                }
              ]
            },
            {
              "name": "Sule",
              "roles": [
                "CB"
              ],
              "archetypePrimary": "Wall",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 85,
                "baseSprint": 87,
                "baseAgility": 80,
                "heightCm": 195,
                "weight": 99,
                "strength": 96,
                "balance": 80,
                "accelType": "lengthy",
                "buildType": "stocky",
                "activePS": [
                  "jockey",
                  "block",
                  "bruiser_plus",
                  "long_ball",
                  "anticipate_plus",
                  "slide_tackle_ps",
                  "first_touch",
                  "pinged",
                  "whipped",
                  "intercept_ps_plus",
                  "aerial"
                ],
                "shortPass": 90,
                "longPass": 93,
                "vision": 83,
                "crossing": 63,
                "curve": 60,
                "fkAccuracy": 46,
                "standTackle": 94,
                "slideTackle": 95,
                "interceptions": 95,
                "headingAcc": 86,
                "defAwareness": 93,
                "aggression": 88,
                "jumping": 95,
                "finishing": 45,
                "shotPower": 93,
                "longShots": 82,
                "volleys": 75,
                "attPositioning": 50,
                "composure": 93,
                "reactions": 94,
                "ballControl": 83,
                "dribbling": 80,
                "stamina": 90
              },
              "effA": 70,
              "effS": 108,
              "effG": 65,
              "effT": 98,
              "effSlip": 49,
              "effPassShort": 96,
              "effPassLong": 111,
              "effPassThrough": 100,
              "effPassCross": 77,
              "effDefTackle": 129,
              "effDefPos": 117,
              "effDefInt": 119,
              "effDefAer": 121,
              "effDefBully": 135,
              "effDefSlide": 115,
              "effShootFin": 56,
              "effShootPwr": 107,
              "effShootFine": 77,
              "effShootVol": 83,
              "effShootLdr": 79,
              "effShootFk": 50,
              "colorTags": [
                {
                  "fill": "#c800d4",
                  "border": "#00dbff"
                }
              ]
            },
            {
              "name": "Tah",
              "roles": [
                "CB"
              ],
              "archetypePrimary": "Wall",
              "archetypeSecondary": "",
              "state": {
                "chemStyle": "shadow",
                "baseAccel": 91,
                "baseSprint": 92,
                "baseAgility": 85,
                "heightCm": 195,
                "weight": 94,
                "strength": 93,
                "balance": 86,
                "accelType": "lengthy",
                "buildType": "stocky",
                "activePS": [
                  "jockey",
                  "block",
                  "precision_header",
                  "bruiser_plus",
                  "anticipate_plus",
                  "slide_tackle_ps",
                  "intercept_ps_plus",
                  "quickstep",
                  "aerial"
                ],
                "shortPass": 92,
                "longPass": 90,
                "vision": 75,
                "crossing": 40,
                "curve": 70,
                "fkAccuracy": 28,
                "standTackle": 95,
                "slideTackle": 94,
                "interceptions": 93,
                "headingAcc": 92,
                "defAwareness": 95,
                "aggression": 92,
                "jumping": 95,
                "finishing": 34,
                "shotPower": 63,
                "longShots": 27,
                "volleys": 56,
                "attPositioning": 38,
                "composure": 93,
                "reactions": 93,
                "ballControl": 85,
                "dribbling": 85,
                "stamina": 90
              },
              "effA": 80,
              "effS": 115,
              "effG": 72,
              "effT": 96,
              "effSlip": 53,
              "effPassShort": 98,
              "effPassLong": 96,
              "effPassThrough": 90,
              "effPassCross": 46,
              "effDefTackle": 127,
              "effDefPos": 121,
              "effDefInt": 118,
              "effDefAer": 133,
              "effDefBully": 133,
              "effDefSlide": 118,
              "effShootFin": 45,
              "effShootPwr": 78,
              "effShootFine": 55,
              "effShootVol": 65,
              "effShootLdr": 61,
              "effShootFk": 35,
              "colorTags": [
                {
                  "fill": "#0058ff",
                  "border": "#00caff"
                },
                {
                  "fill": "#008a00",
                  "border": "#00ff00"
                }
              ]
            }
          ],
          "id": "ti87ek7",
          "subfolders": []
        }
      ]
    }
  ]
};
